<?php

namespace App;

use GrahamCampbell\Markdown\Facades\Markdown;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Laratrust\Traits\LaratrustUserTrait;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;
    use LaratrustUserTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','slug'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];


    //A user can have more than one post
    public function post(){
        return $this->hasMany(Post::class,'author_id');
    }

    public function getRouteKeyName()
     {
//        return parent::getRouteKeyName(); // TODO: Change the autogenerated stub
        return 'slug';
    }

    //Defining an accessor attribute
    public function getAuthorBiographyAttribute($value){
        return Markdown::convertToHtml(e($this->bio));
    }

    public function setPasswordAttribute($value){
        if (!empty($value)){
            $this->attributes['password'] = bcrypt($value);
        }
    }
}
